version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - '5000:5000'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/:/etc/ssl/:ro
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - api
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
